# -*- coding: utf-8 -*-
"""SupportVectorClassifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15BISmmvSpXsTwrqvnk-eWo6_sL_On-eE
"""

import pandas as pd

df = pd.read_csv('diabetes.csv')

df.head()

X = df[df.columns[:8]]

y = df['Outcome']

from sklearn.preprocessing import StandardScaler

# standarisasi nilai-nilai dari dataset
scaler = StandardScaler()
scaler.fit(X)

X = scaler.transform(X)

from sklearn.model_selection import train_test_split

# memisahkan data untuk training dan testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

from sklearn.svm import SVC

# membuat objek SVC dan memanggil fungsi fit untuk melatih model
clf = SVC()
clf.fit(X_train, y_train)

# menampilkan skor akurasi prediksi
clf.score(X_test, y_test)

# Siapkan Data yang akan di Prediksi, misalnya:
pregnancies = 6
glucose = 148
blood_pressure = 72
skin_thickness = 35
insulin = 0
bmi = 33
diabetes_pedigree_function = 0.627
age = 50

# Ubah ke dalam array
data_prediksi = [[pregnancies,
                  glucose,
                  blood_pressure,
                  skin_thickness,
                  insulin,
                  bmi,
                  diabetes_pedigree_function,
                  age
                ]]

# Gunakan scaler untuk standarisasi datanya
data_prediksi = scaler.transform(data_prediksi)

# Lakukan prediksi
hasil = clf.predict(data_prediksi)

# Cetak hasilnya
print(hasil)