# -*- coding: utf-8 -*-
"""cross-validation.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJIOgL98SG57pB1QSIerKOYJY71djDxz
"""

import sklearn
from sklearn import datasets
from sklearn import tree
from sklearn.model_selection import cross_val_score

iris = datasets.load_iris()

x=iris.data
y=iris.target

clf = tree.DecisionTreeClassifier()

scores = cross_val_score(clf, x, y, cv=5)

print(scores)